name: Quick Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install beautifulsoup4 # test dependency
        pip install -r requirements.txt
    - name: Quick Test and Code coverage
      run: |
        make quick_test_coverage
